spring:
  application:
    name: mallservice
  profiles:
    # 指定为开发环境
    active: dev
  datasource:
    driver-class-name: ${mall.datasource.driver-class-name}
    url: ${mall.datasource.url}
    username: ${mall.datasource.username}
    password: ${mall.datasource.password}
  data:
    redis:
      host: ${mall.redis.host}
      port: ${mall.redis.port}
      password: ${mall.redis.password} # docker部署的redis我暂时没有设置密码
      database: ${mall.redis.database}
      lettuce:
        pool:
          max-active: ${mall.redis.lettuce.pool.max-active}
          max-idle: ${mall.redis.lettuce.pool.max-idle}
          min-idle: ${mall.redis.lettuce.pool.min-idle}
          max-wait: ${mall.redis.lettuce.pool.max-wait}
  rabbitmq:
    #ip+端口
    host: ${mall.rabbitmq.host}
    port: ${mall.rabbitmq.port}
    #用户名
    username: ${mall.rabbitmq.username}
    #密码
    password: ${mall.rabbitmq.password}
    #虚拟主机
    virtual-host: ${mall.rabbitmq.virtual-host}
mybatis-plus:
  configuration:
    #自动驼峰命名转化
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml

#配置日志级别
logging:
  level:
    pers.ly.mall.mapper: debug

knife4j:
  #是否启用增强功能
  enable: true
  #生产环境开关
  production: false
  setting:
    #语言
    language: zh_cn
    enable-footer: false


#启动端口
server:
  port: 9090
